### ISSUE TITLE
the problem with make install

### ISSUE THREAD

**Issue by fxm88** [IntelAI/he-transformer#73]
Using local nGraph source in directory  /home/ubuntu/he-transformer/build/ext_ngraph/src/ext_ngraph
Source location: /home/ubuntu/he-transformer/build/ext_ngraph/src/ext_ngraph
Running COMMAND: cmake -DNGRAPH_INSTALL_PREFIX=/home/ubuntu/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/artifacts -DNGRAPH_USE_CXX_ABI=1 -DNGRAPH_DEX_ONLY=TRUE -DNGRAPH_DEBUG_ENABLE=NO -DNGRAPH_UNIT_TEST_ENABLE=NO -DNGRAPH_TARGET_ARCH=native -DNGRAPH_TUNE_ARCH=native -DNGRAPH_TBB_ENABLE=FALSE -DNGRAPH_DISTRIBUTED_ENABLE=OFF -DNGRAPH_TOOLS_ENABLE=YES -DNGRAPH_GPU_ENABLE=NO -DNGRAPH_PLAIDML_ENABLE=NO -DNGRAPH_INTELGPU_ENABLE=NO /home/ubuntu/he-transformer/build/ext_ngraph/src/ext_ngraph
CMake Error: The source directory "/home/ubuntu/he-transformer/build/ext_ngraph/src/ext_ngraph" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "/home/ubuntu/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_ngtf.py", line 525, in <module>
    main()
  File "/home/ubuntu/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_ngtf.py", line 402, in main
    build_ngraph(build_dir, ngraph_src_dir, ngraph_cmake_flags, verbosity)
  File "/home/ubuntu/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/tools/build_utils.py", line 86, in build_ngraph
    command_executor(cmake_cmd, verbose=True)
  File "/home/ubuntu/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/tools/build_utils.py", line 60, in command_executor
    raise Exception("Error running command: " + cmd)
Exception: Error running command: cmake -DNGRAPH_INSTALL_PREFIX=/home/ubuntu/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/artifacts -DNGRAPH_USE_CXX_ABI=1 -DNGRAPH_DEX_ONLY=TRUE -DNGRAPH_DEBUG_ENABLE=NO -DNGRAPH_UNIT_TEST_ENABLE=NO -DNGRAPH_TARGET_ARCH=native -DNGRAPH_TUNE_ARCH=native -DNGRAPH_TBB_ENABLE=FALSE -DNGRAPH_DISTRIBUTED_ENABLE=OFF -DNGRAPH_TOOLS_ENABLE=YES -DNGRAPH_GPU_ENABLE=NO -DNGRAPH_PLAIDML_ENABLE=NO -DNGRAPH_INTELGPU_ENABLE=NO /home/ubuntu/he-transformer/build/ext_ngraph/src/ext_ngraph
CMakeFiles/ext_ngraph_tf.dir/build.make:112: recipe for target 'ext_ngraph_tf/src/ext_ngraph_tf-stamp/ext_ngraph_tf-build' failed
make[2]: *** [ext_ngraph_tf/src/ext_ngraph_tf-stamp/ext_ngraph_tf-build] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ext_ngraph_tf.dir/all' failed
make[1]: *** [CMakeFiles/ext_ngraph_tf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

what should I do to solve this problem

**Comment by YSDB** [comment]
I am not sure about it, but did you want to upgrade nGraph in He-transformer?
